import './globals.css'
import LocalFont from 'next/font/local'

const myFont = LocalFont({
  src:'./Nunito_Sans/nunito_sans_var_2.ttf',

  display:'swap'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  )
}
